Repository GSG-G8/bills-sys, pull requests merged in 2020-06, with the labels that each got.

#19 Sequelize setup
  client/package.json
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/config/createdb.sql
  server/src/database/confiq/build.js
  server/src/database/confiq/build.sql
  server/src/database/confiq/connection.js
  server/src/database/confiq/fakedata.sql
  server/src/index.js
  server/src/models/Bill.js
  server/src/models/Type.js
  server/src/models/User.js
  server/src/models/connection.js
  server/src/models/index.js
  server/src/router.js
Labels: Back

#18 handle server and client error
  .gitignore
  package-lock.json
  server/package-lock.json
  server/package.json
  server/src/controller/error.js
  server/src/models/index.js
Labels: Back

#20 10 insert script
  client/package.json
  package.json
  server/.gitignore
  server/package-lock.json
  server/src/config/data.json
  server/src/config/dbBuild.js
  server/src/models/Bill.js
  server/src/models/Type.js
  server/src/models/User.js
  server/src/models/connection.js
  server/src/models/index.js
  server/src/router.js
Labels: Back

#24 login route
  client/package-lock.json
  package.json
  server/__tests__/queries/users.test.js
  server/__tests__/routes/users.test.js
  server/package-lock.json
  server/package.json
  server/src/app.js
  server/src/config/data.json
  server/src/controller/auth.js
  server/src/controller/index.js
  server/src/controller/validation/loginSchema.js
  server/src/middleware/protectedRoute.js
  server/src/models/connection.js
  server/src/queries/checkEmail.js
  server/src/queries/index.js
  server/src/router.js
Labels: Back

#25 14 bills stats
  server/__tests__/queries/bills.test.js
  server/__tests__/routes/bills.test.js
  server/src/controller/error.js
  server/src/controller/index.js
  server/src/controller/stats/getStats.js
  server/src/models/connection.js
  server/src/queries/getBill.js
  server/src/router.js
  server/src/validation/statsSchema.js
Labels: Back, Route

#27 11 get logout
  package.json
  server/__tests__/queries/bills.test.js
  server/__tests__/routes/bills.test.js
  server/__tests__/routes/users.test.js
  server/package.json
  server/src/app.js
  server/src/config/data.json
  server/src/config/dbBuild.js
  server/src/controller/index.js
  server/src/controller/logout.js
  server/src/controller/stats/getStats.js
  server/src/router.js
Labels: Back

#52 language toggle
  client/package-lock.json
  client/package.json
  client/public/locales/ar.json
  client/public/locales/en.json
  client/src/App/index.js
  client/src/components/LanguageToggle.js
  client/src/components/Layout/Header.js
  client/src/components/ToggleButton.js
  client/src/components/index.js
  client/src/i18n.js
  client/src/index.js
  package.json
Labels: Component, Front
